--- #YAML:1.0
name:                   Mail-Outlook
version:                0.23
abstract:               An mail interface to Microsoft (R) Outlook (R)
author:
  - Barbie <barbie@cpan.org>

license:                artistic_2
distribution_type:      module
installdirs:            site

requires:
  perl:                   5.006
  File::Basename:         0
  Win32::OLE:             0
  Win32::OLE::Const:      0
recommends:
  Test::CPAN::Meta:       0
  Test::CPAN::Meta::JSON: 0
  Test::More:             0.70
  Test::Pod:              1.26
  Test::Pod::Coverage:    1.08
build_requires:
  Cwd:                    0
  IO::File:               0
  Test::More:             0.70

provides:
  Mail::Outlook:
    file:     lib/Mail/Outlook.pm
    version:  0.23
  Mail::Outlook::Folder:
    file:     lib/Mail/Outlook/Folder.pm
    version:  0.23
  Mail::Outlook::Message:
    file:     lib/Mail/Outlook/Message.pm
    version:  0.23
no_index:
  directory:
    - t
    - examples

resources:
  license:    http://www.perlfoundation.org/artistic_license_2_0
  bugtracker: http://rt.cpan.org/Public/Dist/Display.html?Name=Mail-Outlook

meta-spec:
   version:   1.4
   url:       http://module-build.sourceforge.net/META-spec-v1.4.html
generated_by: Hand 1.0
