--- #YAML:1.0
name:                   Mail-Outlook
version:                0.14
abstract:               An mail interface to Microsoft (R) Outlook (R).
author:
  - Barbie <barbie@cpan.org>

license:                perl
distribution_type:      module
installdirs:            site

requires:
  File::Basename:       0
  Win32::OLE:           0
  Win32::OLE::Const:    0
recommends:
  Test::More:           0.70
  Test::Pod:            1.26
  Test::Pod::Coverage:  1.08
  Test::CPAN::Meta:     0.12
build_requires:
  Test::More:           0.70
  Cwd:                  0

provides:
  Mail::Outlook:
    file:     lib/Mail/Outlook.pm
    version:  0.14
  Mail::Outlook::Folder:
    file:     lib/Mail/Outlook/Folder.pm
    version:  0.14
  Mail::Outlook::Message:
    file:     lib/Mail/Outlook/Message.pm
    version:  0.14
no_index:
  directory:
    - t
    - examples

meta-spec:
   version:   1.4
   url:       http://module-build.sourceforge.net/META-spec-v1.4.html
generated_by: Hand 1.0
